import dynamic from 'next/dynamic';
import Head from 'next/head';
import { ReactElement } from 'react';
import Layout from '../components/Layout';
import { NextPageWithLayout } from './_app';

const SwitchTheme = dynamic(
	() => import('../components/partials/SwitchTheme'),
	{
		ssr: false,
	},
);

const Home: NextPageWithLayout = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>
				<p>
					Get started by editing <code>pages/index.tsx</code>
				</p>
				<SwitchTheme />
			</main>
		</div>
	);
};

Home.getLayout = function getLayout(page: ReactElement) {
	return <Layout>{page}</Layout>;
};

export default Home;
